name: Publish Package

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Copy settings.xml to default Maven location
        run: cp .github/workflows/settings.xml ~/.m2/settings.xml

      - name: Grant execute permission to Maven Wrapper
        run: chmod +x ./mvnw

      - name: Print Token
        run: |
          echo "Token=${{ secrets.TOKEN }}"      

      - name: Publish package
        run: ./mvnw deploy
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_ACTOR: JayasriChinthala