name: Publish Package

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          server-id: github
          settings-path: settings.xml

      - name: Grant execute permission to Maven Wrapper
        run: chmod +x ./mvnw

      - name: Publish package
        run: ./mvnw deploy
        env:
          GITHUB_TOKEN: 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
          GITHUB_ACTOR: rajeshchettupalli-achala